// File: airport-data.js
const airportData = {
"type": "FeatureCollection",
"features": [
{"type":"Feature","geometry":{"type":"Point","coordinates":[-75.4404,40.6521]},"properties":{"code":"ABE","name":"Lehigh Valley International Airport","city":"Allentown","state":"PA"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-106.6092,35.0402]},"properties":{"code":"ABQ","name":"Albuquerque International Sunport","city":"Albuquerque","state":"NM"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-75.1826,39.8744]},"properties":{"code":"ACY","name":"Atlantic City International","city":"Atlantic City","state":"NJ"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-73.8017,42.7483]},"properties":{"code":"ALB","name":"Albany International Airport","city":"Albany","state":"NY"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-149.9964,61.1744]},"properties":{"code":"ANC","name":"Ted Stevens Anchorage International","city":"Anchorage","state":"AK"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-84.4281,33.6367]},"properties":{"code":"ATL","name":"Hartsfield-Jackson Atlanta International","city":"Atlanta","state":"GA"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-88.1296,44.2619]},"properties":{"code":"ATW","name":"Appleton International Airport","city":"Appleton","state":"WI"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-97.6699,30.1945]},"properties":{"code":"AUS","name":"Austin-Bergstrom International Airport","city":"Austin","state":"TX"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-82.5541,35.8111]},"properties":{"code":"AVL","name":"Asheville Regional Airport","city":"Asheville","state":"NC"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-72.6832,41.939]},"properties":{"code":"BDL","name":"Bradley International Airport","city":"Windsor Locks","state":"CT"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-86.7535,33.5629]},"properties":{"code":"BHM","name":"Birmingham-Shuttlesworth International Airport","city":"Birmingham","state":"AL"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-122.5360,48.7923]},"properties":{"code":"BLI","name":"Bellingham International Airport","city":"Bellingham","state":"WA"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-86.7703,36.1245]},"properties":{"code":"BNA","name":"Nashville International Airport","city":"Nashville","state":"TN"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-116.2229,43.5644]},"properties":{"code":"BOI","name":"Boise Airport","city":"Boise","state":"ID"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-71.0052,42.3643]},"properties":{"code":"BOS","name":"Boston Logan International","city":"Boston","state":"MA"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-73.1533,42.9429]},"properties":{"code":"BTV","name":"Burlington International Airport","city":"Burlington","state":"VT"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-78.7322,42.9405]},"properties":{"code":"BUF","name":"Buffalo Niagara International Airport","city":"Buffalo","state":"NY"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-118.3585,34.2006]},"properties":{"code":"BUR","name":"Hollywood Burbank Airport","city":"Burbank","state":"CA"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-76.6683,39.1754]},"properties":{"code":"BWI","name":"Baltimore/Washington International Thurgood Marshall","city":"Baltimore","state":"MD"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-111.153,45.7775]},"properties":{"code":"BZN","name":"Bozeman Yellowstone International Airport","city":"Bozeman","state":"MT"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-81.1195,33.9388]},"properties":{"code":"CAE","name":"Columbia Metropolitan Airport","city":"Columbia","state":"SC"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-85.2035,35.0353]},"properties":{"code":"CHA","name":"Chattanooga Metropolitan Airport","city":"Chattanooga","state":"TN"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-80.6549,32.8986]},"properties":{"code":"CHS","name":"Charleston International Airport","city":"Charleston","state":"SC"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-91.7109,41.8847]},"properties":{"code":"CID","name":"Eastern Iowa Airport","city":"Cedar Rapids","state":"IA"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-81.8547,41.4094]},"properties":{"code":"CLE","name":"Cleveland Hopkins International","city":"Cleveland","state":"OH"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-80.9431,35.214]},"properties":{"code":"CLT","name":"Charlotte Douglas International","city":"Charlotte","state":"NC"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-82.8919,39.998]},"properties":{"code":"CMH","name":"John Glenn Columbus International Airport","city":"Columbus","state":"OH"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-104.7008,38.8058]},"properties":{"code":"COS","name":"Colorado Springs Airport","city":"Colorado Springs","state":"CO"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-84.6678,39.0488]},"properties":{"code":"CVG","name":"Cincinnati/Northern Kentucky International","city":"Cincinnati","state":"KY"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-96.8518,32.8471]},"properties":{"code":"DAL","name":"Dallas Love Field","city":"Dallas","state":"TX"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-84.2194,39.9024]},"properties":{"code":"DAY","name":"Dayton International","city":"Dayton","state":"OH"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-77.0377,38.8521]},"properties":{"code":"DCA","name":"Ronald Reagan Washington National","city":"Washington","state":"DC"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-104.6732,39.8617]},"properties":{"code":"DEN","name":"Denver International","city":"Denver","state":"CO"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-97.038,32.8968]},"properties":{"code":"DFW","name":"Dallas/Fort Worth International","city":"Dallas/Fort Worth","state":"TX"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-93.669,41.534]},"properties":{"code":"DSM","name":"Des Moines International Airport","city":"Des Moines","state":"IA"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-83.3534,42.2124]},"properties":{"code":"DTW","name":"Detroit Metropolitan Wayne County","city":"Detroit","state":"MI"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-85.7954,30.3571]},"properties":{"code":"ECP","name":"Northwest Florida Beaches International Airport","city":"Panama City Beach","state":"FL"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-106.6092,31.8067]},"properties":{"code":"ELP","name":"El Paso International Airport","city":"El Paso","state":"TX"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-123.211,44.1246]},"properties":{"code":"EUG","name":"Eugene Airport","city":"Eugene","state":"OR"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-74.1687,40.6925]},"properties":{"code":"EWR","name":"Newark Liberty International","city":"Newark","state":"NJ"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-81.7596,24.5561]},"properties":{"code":"EYW","name":"Key West International Airport","city":"Key West","state":"FL"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-147.8564,64.8151]},"properties":{"code":"FAI","name":"Fairbanks International Airport","city":"Fairbanks","state":"AK"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-96.8158,46.9207]},"properties":{"code":"FAR","name":"Hector International Airport","city":"Fargo","state":"ND"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-119.718,36.7762]},"properties":{"code":"FAT","name":"Fresno Yosemite International Airport","city":"Fresno","state":"CA"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-80.1527,26.0726]},"properties":{"code":"FLL","name":"Fort Lauderdale-Hollywood International","city":"Fort Lauderdale","state":"FL"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-83.1943,42.8808]},"properties":{"code":"FNT","name":"Bishop International Airport","city":"Flint","state":"MI"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-96.7419,43.582]},"properties":{"code":"FSD","name":"Joe Foss Field","city":"Sioux Falls","state":"SD"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-117.5342,47.6192]},"properties":{"code":"GEG","name":"Spokane International","city":"Spokane","state":"WA"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-85.5228,42.8808]},"properties":{"code":"GRR","name":"Gerald R. Ford International Airport","city":"Grand Rapids","state":"MI"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-79.9373,36.0978]},"properties":{"code":"GSO","name":"Piedmont Triad International Airport","city":"Greensboro","state":"NC"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-82.2189,34.8957]},"properties":{"code":"GSP","name":"Greenville-Spartanburg International Airport","city":"Greer","state":"SC"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[144.797,13.484]},"properties":{"code":"GUM","name":"Antonio B. Won Pat International Airport","city":"Tamuning","state":"GU"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-157.9224,21.3187]},"properties":{"code":"HNL","name":"Daniel K. Inouye International (Honolulu)","city":"Honolulu","state":"HI"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-95.2789,29.6454]},"properties":{"code":"HOU","name":"William P. Hobby (Houston)","city":"Houston","state":"TX"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-73.7076,41.067]},"properties":{"code":"HPN","name":"Westchester County Airport","city":"White Plains","state":"NY"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-97.6544,26.2285]},"properties":{"code":"HRL","name":"Valley International Airport","city":"Harlingen","state":"TX"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-86.7751,34.6372]},"properties":{"code":"HSV","name":"Huntsville International Airport","city":"Huntsville","state":"AL"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-72.7756,41.2637]},"properties":{"code":"HVN","name":"Tweed-New Haven Regional Airport","city":"New Haven","state":"CT"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-70.2804,41.6693]},"properties":{"code":"HYA","name":"Barnstable Municipal Airport","city":"Hyannis","state":"MA"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-77.4558,38.9445]},"properties":{"code":"IAD","name":"Washington Dulles International","city":"Washington","state":"VA"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-95.3414,29.9844]},"properties":{"code":"IAH","name":"George Bush Intercontinental (Houston)","city":"Houston","state":"TX"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-97.4331,37.6499]},"properties":{"code":"ICT","name":"Wichita Dwight D. Eisenhower National Airport","city":"Wichita","state":"KS"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-75.4404,39.6787]},"properties":{"code":"ILG","name":"Wilmington Airport","city":"Wilmington","state":"DE"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-77.9026,34.2706]},"properties":{"code":"ILM","name":"Wilmington International Airport","city":"Wilmington","state":"NC"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-83.7921,39.4279]},"properties":{"code":"ILN","name":"Wilmington Air Park","city":"Wilmington","state":"OH"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-86.2944,39.7173]},"properties":{"code":"IND","name":"Indianapolis International","city":"Indianapolis","state":"IN"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-112.6738,33.3077]},"properties":{"code":"IWA","name":"Phoenix-Mesa Gateway Airport","city":"Mesa","state":"AZ"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-90.0812,32.3112]},"properties":{"code":"JAN","name":"Jackson-Medgar Wiley Evers International Airport","city":"Jackson","state":"MS"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-81.6874,30.4919]},"properties":{"code":"JAX","name":"Jacksonville International Airport","city":"Jacksonville","state":"FL"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-73.7789,40.6398]},"properties":{"code":"JFK","name":"John F. Kennedy International (New York)","city":"New York","state":"NY"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-81.7552,27.9889]},"properties":{"code":"LAL","name":"Lakeland Linder International Airport","city":"Lakeland","state":"FL"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-115.1522,36.0801]},"properties":{"code":"LAS","name":"Harry Reid International (Las Vegas)","city":"Las Vegas","state":"NV"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-118.4081,33.9425]},"properties":{"code":"LAX","name":"Los Angeles International","city":"Los Angeles","state":"CA"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-101.8206,33.6636]},"properties":{"code":"LBB","name":"Lubbock Preston Smith International Airport","city":"Lubbock","state":"TX"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-84.3503,38.0365]},"properties":{"code":"LEX","name":"Blue Grass Airport","city":"Lexington","state":"KY"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-73.8726,40.7772]},"properties":{"code":"LGA","name":"LaGuardia (New York)","city":"New York","state":"NY"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-118.1516,33.8177]},"properties":{"code":"LGB","name":"Long Beach Airport","city":"Long Beach","state":"CA"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-92.4736,34.7294]},"properties":{"code":"LIT","name":"Bill and Hillary Clinton National Airport","city":"Little Rock","state":"AR"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-102.2019,31.9475]},"properties":{"code":"MAF","name":"Midland International Air and Space Port","city":"Midland","state":"TX"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-94.3069,39.2976]},"properties":{"code":"MCI","name":"Kansas City International Airport","city":"Kansas City","state":"MO"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-81.3089,28.4294]},"properties":{"code":"MCO","name":"Orlando International","city":"Orlando","state":"FL"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-76.9264,40.1935]},"properties":{"code":"MDT","name":"Harrisburg International Airport","city":"Middletown","state":"PA"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-87.7524,41.786]},"properties":{"code":"MDW","name":"Chicago Midway International","city":"Chicago","state":"IL"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-89.9767,35.0424]},"properties":{"code":"MEM","name":"Memphis International Airport","city":"Memphis","state":"TN"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-122.8726,42.3721]},"properties":{"code":"MFR","name":"Rogue Valley International-Medford","city":"Medford","state":"OR"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-71.289,42.9304]},"properties":{"code":"MHT","name":"Manchester-Boston Regional Airport","city":"Manchester","state":"NH"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-80.2906,25.7933]},"properties":{"code":"MIA","name":"Miami International","city":"Miami","state":"FL"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-87.8966,43.1399]},"properties":{"code":"MKE","name":"Milwaukee Mitchell International Airport","city":"Milwaukee","state":"WI"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-89.3375,43.1399]},"properties":{"code":"MSN","name":"Dane County Regional Airport","city":"Madison","state":"WI"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-93.2218,44.882]},"properties":{"code":"MSP","name":"Minneapolis-St. Paul International","city":"Minneapolis","state":"MN"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-90.0701,29.9934]},"properties":{"code":"MSY","name":"Louis Armstrong New Orleans International Airport","city":"New Orleans","state":"LA"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-78.8805,33.6798]},"properties":{"code":"MYR","name":"Myrtle Beach International Airport","city":"Myrtle Beach","state":"SC"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-73.82575,40.7085]},"properties":{"code":"NYC","name":"New York City (LGA/JFK)","city":"New York","state":"NY"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-122.2207,37.7213]},"properties":{"code":"OAK","name":"Oakland International","city":"Oakland","state":"CA"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-95.8942,41.3032]},"properties":{"code":"OMA","name":"Eppley Airfield","city":"Omaha","state":"NE"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-117.6012,34.056]},"properties":{"code":"ONT","name":"Ontario International","city":"Ontario","state":"CA"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-87.9048,41.9786]},"properties":{"code":"ORD","name":"Chicago O'Hare International","city":"Chicago","state":"IL"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-76.2012,36.8946]},"properties":{"code":"ORF","name":"Norfolk International Airport","city":"Norfolk","state":"VA"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-122.2817,47.9095]},"properties":{"code":"PAE","name":"Paine Field (Everett)","city":"Everett","state":"WA"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-80.0956,26.6832]},"properties":{"code":"PBI","name":"Palm Beach International Airport","city":"West Palm Beach","state":"FL"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-122.5906,45.5876]},"properties":{"code":"PDX","name":"Portland International","city":"Portland","state":"OR"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-81.9911,26.9202]},"properties":{"code":"PGD","name":"Punta Gorda Airport","city":"Punta Gorda","state":"FL"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-75.2411,39.8719]},"properties":{"code":"PHL","name":"Philadelphia International","city":"Philadelphia","state":"PA"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-112.0116,33.4343]},"properties":{"code":"PHX","name":"Phoenix Sky Harbor International","city":"Phoenix","state":"AZ"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-82.6874,27.9102]},"properties":{"code":"PIE","name":"St. Pete–Clearwater International Airport","city":"Clearwater","state":"FL"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-80.2327,40.4914]},"properties":{"code":"PIT","name":"Pittsburgh International Airport","city":"Pittsburgh","state":"PA"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-87.2199,30.4734]},"properties":{"code":"PNS","name":"Pensacola International Airport","city":"Pensacola","state":"FL"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-116.5063,33.8297]},"properties":{"code":"PSP","name":"Palm Springs International Airport","city":"Palm Springs","state":"CA"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-71.436,41.7249]},"properties":{"code":"PVD","name":"Rhode Island T. F. Green International Airport","city":"Warwick","state":"RI"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-111.6654,40.2165]},"properties":{"code":"PVU","name":"Provo Municipal Airport","city":"Provo","state":"UT"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-70.3093,41.6683]},"properties":{"code":"PWM","name":"Portland International Jetport","city":"Portland","state":"ME"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-121.1504,44.2543]},"properties":{"code":"RDM","name":"Roberts Field","city":"Redmond","state":"OR"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-78.7875,35.8776]},"properties":{"code":"RDU","name":"Raleigh-Durham International","city":"Raleigh","state":"NC"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-77.6724,37.5052]},"properties":{"code":"RIC","name":"Richmond International Airport","city":"Richmond","state":"VA"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-119.7681,39.4991]},"properties":{"code":"RNO","name":"Reno-Tahoe International Airport","city":"Reno","state":"NV"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-77.3197,43.1189]},"properties":{"code":"ROC","name":"Greater Rochester International Airport","city":"Rochester","state":"NY"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-82.5541,26.5362]},"properties":{"code":"RSW","name":"Southwest Florida International Airport","city":"Fort Myers","state":"FL"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-117.1897,32.7336]},"properties":{"code":"SAN","name":"San Diego International Airport","city":"San Diego","state":"CA"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-98.4698,29.5337]},"properties":{"code":"SAT","name":"San Antonio International Airport","city":"San Antonio","state":"TX"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-79.9373,32.8986]},"properties":{"code":"SAV","name":"Savannah/Hilton Head International Airport","city":"Savannah","state":"GA"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-119.8938,34.4262]},"properties":{"code":"SBA","name":"Santa Barbara Municipal Airport","city":"Santa Barbara","state":"CA"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-85.736,38.1744]},"properties":{"code":"SDF","name":"Louisville Muhammad Ali International","city":"Louisville","state":"KY"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-122.3093,47.449]},"properties":{"code":"SEA","name":"Seattle-Tacoma International","city":"Seattle","state":"WA"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-81.2433,28.7776]},"properties":{"code":"SFB","name":"Orlando Sanford International Airport","city":"Sanford","state":"FL"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-122.3755,37.6188]},"properties":{"code":"SFO","name":"San Francisco International","city":"San Francisco","state":"CA"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-93.6607,37.1859]},"properties":{"code":"SGF","name":"Springfield-Branson National Airport","city":"Springfield","state":"MO"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-121.9299,37.3619]},"properties":{"code":"SJC","name":"Norman Y. Mineta San Jose International Airport","city":"San Jose","state":"CA"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-111.9778,40.7884]},"properties":{"code":"SLC","name":"Salt Lake City International","city":"Salt Lake City","state":"UT"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-121.5908,38.6954]},"properties":{"code":"SMF","name":"Sacramento International Airport","city":"Sacramento","state":"CA"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-117.8682,33.6757]},"properties":{"code":"SNA","name":"John Wayne Airport","city":"Santa Ana","state":"CA"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-82.2189,27.3954]},"properties":{"code":"SRQ","name":"Sarasota-Bradenton International Airport","city":"Sarasota","state":"FL"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-90.3613,38.7477]},"properties":{"code":"STL","name":"St. Louis Lambert International","city":"St. Louis","state":"MO"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-76.1063,43.1112]},"properties":{"code":"SYR","name":"Syracuse Hancock International Airport","city":"Syracuse","state":"NY"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-82.5332,27.9755]},"properties":{"code":"TPA","name":"Tampa International","city":"Tampa","state":"FL"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-95.8881,36.1984]},"properties":{"code":"TUL","name":"Tulsa International Airport","city":"Tulsa","state":"OK"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-110.941,32.1161]},"properties":{"code":"TUS","name":"Tucson International Airport","city":"Tucson","state":"AZ"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-83.3538,35.8111]},"properties":{"code":"TYS","name":"McGhee Tyson Airport","city":"Knoxville","state":"TN"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-86.6782,30.4861]},"properties":{"code":"VPS","name":"Destin–Fort Walton Beach Airport","city":"Valparaiso","state":"FL"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-80.3956,27.5432]},"properties":{"code":"VRB","name":"Vero Beach Regional Airport","city":"Vero Beach","state":"FL"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[-94.3633,35.3931]},"properties":{"code":"XNA","name":"Northwest Arkansas National Airport","city":"Bentonville","state":"AR"}}
]
};
